- id: check-branch-staleness
  name: check branch is up-to-date with default branch
  description: >
    Fetches the remote default branch and fails if the current branch is behind.
    Prevents concurrent developers or AI agents from committing against stale state.
    Auto-detects default branch (main, develop, master, etc.).
  entry: hooks/check-branch-staleness.sh
  language: script
  always_run: true
  pass_filenames: false
  stages: [pre-commit]

- id: trivy-deps
  name: trivy (dependency vulnerabilities)
  description: >
    Scans dependency lockfiles (Cargo.lock, package-lock.json, go.sum, etc.)
    for HIGH/CRITICAL CVEs using trivy fs. Complements trivy config which only
    scans IaC/YAML for misconfigurations.
  entry: hooks/trivy-deps.sh
  language: script
  files: (Cargo\.lock|package-lock\.json|go\.sum|requirements\.txt|poetry\.lock|pnpm-lock\.yaml|yarn\.lock|Gemfile\.lock|composer\.lock)$
  stages: [pre-commit]

- id: no-hardcoded-secrets
  name: check for hardcoded secrets
  description: >
    Detects hardcoded passwords, API keys, and secret keys in config files.
    Looks for patterns like password: "base64string..." while ignoring
    template references ($__env{}, secretRef, existingSecret).
    NOTE: superseded by gitleaks/trufflehog for broader coverage; retained
    for repos that cannot install system binaries.
  entry: hooks/no-hardcoded-secrets.sh
  language: script
  types: [yaml]
  stages: [pre-commit]

- id: gitleaks
  name: gitleaks (secret detection)
  description: >
    Scans staged changes for 150+ secret types using pattern matching:
    API keys, tokens, passwords, connection strings, and more.
    Per-repo config: place .gitleaks.toml in repo root to add allowlists.
    Requires: gitleaks in PATH (brew install gitleaks).
  entry: hooks/gitleaks.sh
  language: script
  always_run: true
  pass_filenames: false
  stages: [pre-commit]

- id: trufflehog
  name: trufflehog (verified secret detection)
  description: >
    Scans for secrets using entropy analysis + pattern matching, then verifies
    them against the issuing service. Only fails on confirmed live secrets,
    significantly reducing false positives vs pattern-only tools.
    Complements gitleaks: use both for defense in depth.
    Requires: trufflehog in PATH (brew install trufflehog).
  entry: hooks/trufflehog.sh
  language: script
  always_run: true
  pass_filenames: false
  stages: [pre-commit]

- id: require-signed-commits
  name: require signed commits
  description: >
    Fails if commit.gpgsign is not true or user.signingkey is not set.
    Enforces GPG/SSH commit signing discipline, especially important in
    agentic AI workflows where unsigned commits can slip through
    non-interactive shells.
  entry: hooks/require-signed-commits.sh
  language: script
  always_run: true
  pass_filenames: false
  stages: [pre-commit]
